apiVersion: v1
kind: Secret
metadata:
  name: seldon-operator-webhook-server-secret
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: seldon-operator-controller-manager-service
  namespace: default
spec:
  ports:
  - port: 443
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"

