#! validate-crd: deploy/chart/templates/0000_30_02-clusterserviceversion.crd.yaml
#! parse-kind: ClusterServiceVersion
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: seldonoperator.v1alpha2
  namespace: seldon-operator-system
  annotations:
    capabilities: Seamless Upgrades
    categories: Machine Learning
    description: Deploy, manage and monitor your production machine learning.
    containerImage: seldonio/seldon-core-operator:0.2.8-SNAPSHOT
    createdAt: 2019-05-21T15:00:00Z
    repository: https://github.com/SeldonIO/seldon-operator
    alm-examples: '[{"apiVersion": "machinelearning.seldon.io/v1alpha2","kind": "SeldonDeployment","metadata": {"labels": {"app": "seldon"},"name": "seldon-model"},"spec": {"name": "test-deployment","oauth_key": "oauth-key","oauth_secret": "oauth-secret","predictors": [{"componentSpecs": [{"spec": {"containers": [{"image": "seldonio/mock_classifier:1.0","imagePullPolicy": "IfNotPresent","name": "classifier","resources": {"requests": {"memory": "1Mi"}}}],"terminationGracePeriodSeconds": 1}}],"graph": {"children": [],"name": "classifier","endpoint": {"type" : "REST"},"type": "MODEL"},"name": "example","replicas": 1,"labels": {"version" : "v1"}}]}}]'
    certified: "false"
    support: Clive Cox
spec:
  replaces: seldonoperator.v1alpha1
  displayName: Seldon Operator
  description: |
    The Seldon operator for management, monitoring and operations of machine learning systems through the Seldon Engine.
    Once installed, the Seldon Operator provides multiple functions which facilitate the interaction with machine learning systems.
  keywords: ['machine learning', 'mlops', 'aiops', 'production', 'monitoring']

  maintainers:
  - name: Seldon Technologies
    email: hello@seldon.io

  provider:
    name: Seldon Technologies

  links:
  - name: Website
    url: https://www.seldon.io/
  - name: Documentation
    url: https://docs.seldon.io/projects/seldon-core/en/latest/
  - name: Seldon Operator
    url: https://github.com/seldonio/seldon-operator

  labels:
    name: seldon-operator
  selector:
    matchLabels:
      name: seldon-operator
  installModes:
  - type: OwnNamespace
    supported: true
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: false
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: default
        rules:
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - apps
          resources:
          - deployments/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - v1
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - v1
          resources:
          - services/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - autoscaling
          resources:
          - horizontalpodautoscalers/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - machinelearning.seldon.io
          resources:
          - seldondeployments
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - machinelearning.seldon.io
          resources:
          - seldondeployments/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          - validatingwebhookconfigurations
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      deployments:
      - name: seldon-operator-controller-manager
        spec:
          selector:
            matchLabels:
              control-plane: controller-manager
              controller-tools.k8s.io: "1.0"
          serviceName: seldon-operator-controller-manager-service
          template:
            metadata:
              annotations:
                prometheus.io/scrape: "true"
              labels:
                control-plane: controller-manager
                controller-tools.k8s.io: "1.0"
            spec:
              containers:
              - command:
                - /manager
                env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: SECRET_NAME
                  value: seldon-operator-webhook-server-secret
                image: seldonio/seldon-core-operator:0.2.8-SNAPSHOT
                imagePullPolicy: IfNotPresent
                name: manager
                ports:
                - containerPort: 8080
                  name: metrics
                  protocol: TCP
                - containerPort: 9876
                  name: webhook-server
                  protocol: TCP
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                volumeMounts:
                - mountPath: /tmp/cert
                  name: cert
                  readOnly: true
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: seldon-operator-webhook-server-secret
  customresourcedefinitions:
    owned:
    - name: seldondeployments.machinelearning.seldon.io
      kind: SeldonDeployment
      version: v1alpha2
      displayName: SeldonDelpoyment
      description: A seldon engine deployment
